### ISSUE TITLE
6.0.3.2 can't compile version, sourcecode is missing in repository

### ISSUE THREAD

**Issue by CuteSC2** [SpecialCoins/bitcoincz#1]
Hello, I Provide RPM packages for bcz. Sadly version version 6.0.3.2 didn't build at all.
I think there are some files Missing.
![Screenshot_20200509_214217](https://user-images.githubusercontent.com/49342834/81483392-14a1d800-923e-11ea-92bd-9de24cf43993.png)

How to reproduce
clone fresh repository and change to version 6.0.3.2
./autogen.sh
./configure --with-qtcharts
make

**Comment by lyra00** [comment]
I found out that bczd.cpp maybe is the only missing file, i reuse the pivxd.cpp from older commits and try to compile a working version with that, but for production usage i need sources that can be build

**Comment by SPC-beta** [comment]
fixed on 6.3.2, the master
